library(quantmod)
library(dplyr)
library(data.table)
symbolsH<-c("PDCO","HCN","PKI","SPXL","ADP","VOO","DIA","SH","GLD","MDT")
symbolsWATCH<-c("PXD","CVX","STT","ADSK")
symbolsDOW<-c("AAPL","AXP","BA","CAT","CSCO","CVX","KO","DD","XOM","GE","GS","HD","IBM","INTC",
  "JNJ","JPM","MCD","MMM","MRK","MSFT","NKE","PFE","PG","TRV","UNH","UTX","V","VZ","WMT","DIS")
symbols<-"KLAC"
symbols<-symbolsY
for (i in match("FE",symbols):length(symbols)){
  loadSymbols(Symbols = symbols[i])
}
loadSymbols(Symbols = symbols[40:49])
Results<-NULL
Bounces<-NULL
for (j in 1:length(symbols)){
  Last<-200
  STOCK<-get(symbols[j])
  colnames(STOCK)<-c("open","high","low","close","volume","adjusted")
  if(length(STOCK$open)<Last){
    Last<-length(STOCK$open)
  }
  STOCK<-STOCK[(length(STOCK$open)-Last):length(STOCK$open),]
  STOCK$row<-1:length(STOCK$open)
  STOCK$pCHANGE<-(STOCK$close-STOCK$open)/STOCK$open*100
  STOCK$UP<-0
  STOCK$UP[STOCK$close>STOCK$open]<-1
  streak<-data.frame(unclass(rle(as.vector(STOCK$UP))))
  streak$values[streak$values==0]<--1
  streak$tvalue<-streak$lengths*streak$values
  y<-as.vector(NULL)
  for(i in 1:length(streak$lengths)){
    y<-c(y,rep(streak$tvalue[i],times=streak$lengths[i]))
  }
  STOCK<-cbind(STOCK,y)
  STOCK$NEXT<-stats::lag(STOCK$UP,-1)
  STOCK$NEXT2<-stats::lag(STOCK$UP,-2)
  STOCK$DU<-0
  STOCK$UU<-0
  STOCK$DU[(STOCK$UP-STOCK$NEXT)==-1]<-1
  STOCK$UU[(STOCK$UP == 1 & STOCK$NEXT ==1)]<-1
  STOCK<-as.data.frame(STOCK)
  STOCK.DOWN<-STOCK[STOCK$UP==0,]
  STOCK.DOWN$row<-1:length(STOCK.DOWN$row)
  STOCK.DOWN$pDU<-cumsum(STOCK.DOWN$DU)/STOCK.DOWN$row
  STOCK.UP<-STOCK[STOCK$UP==1,]
  STOCK.UP$row<-1:length(STOCK.UP$row)
  STOCK.UP$pUU<-cumsum(STOCK.UP$UU)/STOCK.UP$row
  y<-as.matrix(as.data.frame(table(STOCK.DOWN$..2)))
  y<-cbind(y,as.numeric(y[,2])/as.numeric(y[,1]))
  y<-cbind(y,cumsum(y[,3]))
  y<-cbind(y,as.numeric(lag(y[,4],1))/as.numeric(y[,4]))
  y2<-as.matrix(as.data.frame(table(STOCK.UP$..2)))
  y2<-cbind(y2,as.numeric(y2[,2])/as.numeric(y2[,1]))
  y2<-cbind(y2,rev(cumsum(rev(y2[,3]))))
  y2<-cbind(y2,(as.numeric(lead(y2[,4],1)))/as.numeric(y2[,4]))
  y3<-rbind(y,y2)
  y3<-cbind(y3,as.numeric(y3[,5])/as.numeric(y3[,1]))
  row<-match(TRUE,(STOCK[length(STOCK$open),10]==y3[,1]))
  Result<-c(symbols[j],STOCK[length(STOCK$open),10],y3[row,5],
    sum(as.numeric(y3[abs(as.numeric(y3[,1]))<(min(abs(range(as.numeric(y3[,1])))-1)),6]),na.rm=TRUE))
  Bounce<-c(symbols[j],y3[y3[,1]==-1,c(4,5)])
  Results<-rbind(Results,Result)
  Bounces<-rbind(Bounces,Bounce)
}

q<-getQuote(symbols)
q$V1<-rownames(q)
real<-merge(Results,q)
View(real)

real$today<-sign(real$Change)
real$streak<-sign(as.numeric(as.matrix(real$V2)))
real$Next<-0
real$V2<-as.numeric(as.matrix(real$V2))
real$Next[real$streak==real$today]<-real$V2[real$streak==real$today]+real$today[real$streak==real$today]
real$Next[real$Next==0]<-real$today[real$Next==0]

rerun<-select(real,V1,V4,V2,V3,Next)
rerun$Next[rerun$Next==0]<--1
symbols2<-as.character(rerun$V1)
Results2<-NULL
for (j in 1:length(symbols2)){
  Last<-2000
  STOCK<-get(symbols2[j])
  colnames(STOCK)<-c("open","high","low","close","volume","adjusted")
  if(length(STOCK$open)<Last){
    Last<-length(STOCK$open)
  }
  STOCK<-STOCK[(length(STOCK$open)-Last):length(STOCK$open),]
  STOCK$row<-1:length(STOCK$open)
  STOCK$pCHANGE<-(STOCK$close-STOCK$open)/STOCK$open*100
  STOCK$UP<-0
  STOCK$UP[STOCK$close>STOCK$open]<-1
  streak<-data.frame(unclass(rle(as.vector(STOCK$UP))))
  streak$values[streak$values==0]<--1
  streak$tvalue<-streak$lengths*streak$values
  y<-as.vector(NULL)
  for(i in 1:length(streak$lengths)){
    y<-c(y,rep(streak$tvalue[i],times=streak$lengths[i]))
  }
  STOCK<-cbind(STOCK,y)
  STOCK$NEXT<-stats::lag(STOCK$UP,-1)
  STOCK$NEXT2<-stats::lag(STOCK$UP,-2)
  STOCK$DU<-0
  STOCK$UU<-0
  STOCK$DU[(STOCK$UP-STOCK$NEXT)==-1]<-1
  STOCK$UU[(STOCK$UP == 1 & STOCK$NEXT ==1)]<-1
  STOCK<-as.data.frame(STOCK)
  STOCK.DOWN<-STOCK[STOCK$UP==0,]
  STOCK.DOWN$row<-1:length(STOCK.DOWN$row)
  STOCK.DOWN$pDU<-cumsum(STOCK.DOWN$DU)/STOCK.DOWN$row
  STOCK.UP<-STOCK[STOCK$UP==1,]
  STOCK.UP$row<-1:length(STOCK.UP$row)
  STOCK.UP$pUU<-cumsum(STOCK.UP$UU)/STOCK.UP$row
  y<-as.matrix(as.data.frame(table(STOCK.DOWN$..2)))
  y<-cbind(y,as.numeric(y[,2])/as.numeric(y[,1]))
  y<-cbind(y,cumsum(y[,3]))
  y<-cbind(y,as.numeric(lag(y[,4],1))/as.numeric(y[,4]))
  y2<-as.matrix(as.data.frame(table(STOCK.UP$..2)))
  y2<-cbind(y2,as.numeric(y2[,2])/as.numeric(y2[,1]))
  y2<-cbind(y2,rev(cumsum(rev(y2[,3]))))
  y2<-cbind(y2,(as.numeric(lead(y2[,4],1)))/as.numeric(y2[,4]))
  y3<-rbind(y,y2)
  y3<-cbind(y3,as.numeric(y3[,5])/as.numeric(y3[,1]))
  row<-match(TRUE,(rerun$Next[j]==y3[,1]))
  Result2<-c(symbols2[j],rerun$Next[j],y3[row,5])
  Results2<-rbind(Results2,Result2)
}
Results2<-as.data.frame(Results2)
colnames(Results2)<-c("V1","Next","pNext")
Final<-left_join(rerun,Results2,by="V1")
Final$pNext<-as.numeric(as.matrix(Final$pNext))
Final$prank[sign(Final$Next.x)==1]<-(Final$pNext[sign(Final$Next.x)==1]-mean(Final$pNext[sign(Final$Next.x)==1],na.rm=TRUE))/sd(Final$Next.x[sign(Final$Next.x)==1],na.rm=TRUE)
Final$prank[sign(Final$Next.x)==-1]<-(Final$pNext[sign(Final$Next.x)==-1]-mean(Final$pNext[sign(Final$Next.x)==-1],na.rm=TRUE))/sd(Final$Next.x[sign(Final$Next.x)==-1],na.rm=TRUE)
Final$pUP[sign(Final$Next.x)==1]<-Final$pNext[sign(Final$Next.x)==1]
Final$pUP[sign(Final$Next.x)==-1]<-1-Final$pNext[sign(Final$Next.x)==-1]
Final$upscore<-Final$pUP*as.numeric(as.matrix(Final$V4))
Final$upscorerank<-(Final$upscore-mean(Final$upscore,na.rm = TRUE))/sd(Final$upscore,na.rm = TRUE)
View(Final)

STT2$V6<-as.numeric(as.matrix(STT2$V5))/as.numeric(as.matrix(STT2$Var1))

symbolsSP<-c(
"MMM",
"ABT",
"ABBV",
"ACN",
"ATVI",
"AYI",
"ADBE",
"AMD",
"AAP",
"AES",
"AET",
"AMG",
"AFL",
"A",
"APD",
"AKAM",
"ALK",
"ALB",
"ARE",
"ALXN",
"ALLE",
"AGN",
"ADS",
"LNT",
"ALL",
"GOOGL",
"GOOG",
"MO",
"AMZN",
"AEE",
"AAL",
"AEP",
"AXP",
"AIG",
"AMT",
"AWK",
"AMP",
"ABC",
"AME",
"AMGN",
"APH",
"APC",
"ADI",
"ANTM",
"AON",
"APA",
"AIV",
"AAPL",
"AMAT",
"ADM",
"ARNC",
"AJG",
"AIZ",
"T",
"ADSK",
"ADP",
"AN",
"AZO",
"AVB",
"AVY",
"BHI",
"BLL",
"BAC",
"BK",
"BCR",
"BAX",
"BBT",
"BDX",
"BBBY",
"BBY",
"BIIB",
"BLK",
"HRB",
"BA",
"BWA",
"BXP",
"BSX",
"BMY",
"AVGO",
"CHRW",
"CA",
"COG",
"CPB",
"COF",
"COP",
"CAH",
"CBOE",
"KMX",
"CCL",
"CAT",
"CBG",
"CBS",
"CELG",
"CNC",
"CNP",
"CTL",
"CERN",
"CF",
"SCHW",
"CHTR",
"CHK",
"CVX",
"CMG",
"CB",
"CHD",
"CI",
"XEC",
"CINF",
"CTAS",
"CSCO",
"C",
"CFG",
"CTXS",
"CLX",
"CME",
"CMS",
"COH",
"KO",
"CTSH",
"CL",
"CMCSA",
"CMA",
"CAG",
"CXO",
"ED",
"STZ",
"COO",
"GLW",
"COST",
"COTY",
"CCI",
"CSRA",
"CSX",
"CMI",
"CVS",
"DHI",
"DHR",
"DRI",
"DVA",
"DE",
"DLPH",
"DAL",
"XRAY",
"DVN",
"DLR",
"DFS",
"DISCA",
"DISCK",
"DISH",
"DG",
"DLTR",
"D",
"DOV",
"DOW",
"DPS",
"DTE",
"DD",
"DUK",
"DXC",
"ETFC",
"EMN",
"ETN",
"EBAY",
"ECL",
"EIX",
"EW",
"EA",
"EMR",
"ETR",
"EVHC",
"EOG",
"EQT",
"EFX",
"EQIX",
"EQR",
"ESS",
"EL",
"ES",
"EXC",
"EXPE",
"EXPD",
"ESRX",
"EXR",
"XOM",
"FFIV",
"FB",
"FAST",
"FRT",
"FDX",
"FIS",
"FITB",
"FE",
"FISV",
"FLIR",
"FLS",
"FLR",
"FMC",
"FL",
"F",
"FTV",
"FBHS",
"BEN",
"FCX",
"GPS",
"GRMN",
"IT",
"GD",
"GE",
"GGP",
"GIS",
"GM",
"GPC",
"GILD",
"GPN",
"GS",
"GT",
"GWW",
"HAL",
"HBI",
"HOG",
"HRS",
"HIG",
"HAS",
"HCA",
"HCP",
"HP",
"HSIC",
"HSY",
"HES",
"HPE",
"HOLX",
"HD",
"HON",
"HRL",
"HST",
"HPQ",
"HUM",
"HBAN",
"IDXX",
"ITW",
"ILMN",
"IR",
"INTC",
"ICE",
"IBM",
"INCY",
"IP",
"IPG",
"IFF",
"INTU",
"ISRG",
"IVZ",
"IRM",
"JEC",
"JBHT",
"SJM",
"JNJ",
"JCI",
"JPM",
"JNPR",
"KSU",
"K",
"KEY",
"KMB",
"KIM",
"KMI",
"KLAC",
"KSS",
"KHC",
"KR",
"LB",
"LLL",
"LH",
"LRCX",
"LEG",
"LEN",
"LVLT",
"LUK",
"LLY",
"LNC",
"LKQ",
"LMT",
"L",
"LOW",
"LYB",
"MTB",
"MAC",
"M",
"MNK",
"MRO",
"MPC",
"MAR",
"MMC",
"MLM",
"MAS",
"MA",
"MAT",
"MKC",
"MCD",
"MCK",
"MJN",
"MDT",
"MRK",
"MET",
"MTD",
"KORS",
"MCHP",
"MU",
"MSFT",
"MAA",
"MHK",
"TAP",
"MDLZ",
"MON",
"MNST",
"MCO",
"MS",
"MOS",
"MSI",
"MUR",
"MYL",
"NDAQ",
"NOV",
"NAVI",
"NTAP",
"NFLX",
"NWL",
"NFX",
"NEM",
"NWSA",
"NWS",
"NEE",
"NLSN",
"NKE",
"NI",
"NBL",
"JWN",
"NSC",
"NTRS",
"NOC",
"NRG",
"NUE",
"NVDA",
"ORLY",
"OXY",
"OMC",
"OKE",
"ORCL",
"PCAR",
"PH",
"PDCO",
"PAYX",
"PYPL",
"PNR",
"PBCT",
"PEP",
"PKI",
"PRGO",
"PFE",
"PCG",
"PM",
"PSX",
"PNW",
"PXD",
"PNC",
"RL",
"PPG",
"PPL",
"PX",
"PCLN",
"PFG",
"PG",
"PGR",
"PLD",
"PRU",
"PEG",
"PSA",
"PHM",
"PVH",
"QRVO",
"PWR",
"QCOM",
"DGX",
"RRC",
"RJF",
"RTN",
"O",
"RHT",
"REG",
"REGN",
"RF",
"RSG",
"RAI",
"RHI",
"ROK",
"COL",
"ROP",
"ROST",
"RCL",
"R",
"CRM",
"SCG",
"SLB",
"SNI",
"STX",
"SEE",
"SRE",
"SHW",
"SIG",
"SPG",
"SWKS",
"SLG",
"SNA",
"SO",
"LUV",
"SPGI",
"SWK",
"SPLS",
"SBUX",
"STT",
"SRCL",
"SYK",
"STI",
"SYMC",
"SYF",
"SNPS",
"SYY",
"TROW",
"TGT",
"TEL",
"FTI",
"TGNA",
"TDC",
"TSO",
"TXN",
"TXT",
"TMO",
"TIF",
"TWX",
"TJX",
"TMK",
"TSS",
"TSCO",
"TDG",
"RIG",
"TRV",
"TRIP",
"FOXA",
"FOX",
"TSN",
"UDR",
"ULTA",
"USB",
"UA",
"UAA",
"UNP",
"UAL",
"UNH",
"UPS",
"URI",
"UTX",
"UHS",
"UNM",
"VFC",
"VLO",
"VAR",
"VTR",
"VRSN",
"VRSK",
"VZ",
"VRTX",
"VIAB",
"V",
"VNO",
"VMC",
"WMT",
"WBA",
"DIS",
"WM",
"WAT",
"WEC",
"WFC",
"HCN",
"WDC",
"WU",
"WRK",
"WY",
"WHR",
"WFM",
"WMB",
"WLTW",
"WYN",
"WYNN",
"XEL",
"XRX",
"XLNX",
"XL",
"XYL",
"YHOO",
"YUM",
"ZBH",
"ZION",
"ZTS")
